---
output: pdf_document
---

# Impact of Inflation On Stock Market Performance -- A Canadian Perspective (With Code)
**Although this is not the full analysis for part 3, you may find the notes in this document helpful as supplements to the full analysis.**

## Setup

```{r}
# Import data
df <- read.csv("/Users/daniel/Dev/STA302-FINAL-PROJECT/Part 1/cleaned_df.csv")
# Verifies that the data is imported correctly
str(df)
```

Now we will separate the dataset into training set and test set

```{r}
# Create a 50/50 split
set.seed(1)
# Opted for a higher number of samples to include in the training dataset
train_df <- df[sample(1:nrow(df), ceiling(nrow(df)/2), replace=F), ]
test_df <- df[which(!(df$X %in% train_df$X)), ]

# Delete the index column that was used to separate the training and testing data sets
train_df <- train_df[!(names(train_df) %in% c("X"))]
test_df <- test_df[!(names(test_df) %in% c("X"))]

# Verify the training and testing data sets have the right number of samples
dim(train_df)
dim(test_df)
```









